---
# MongoDB with sample application
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_backups:/data/backups
      - ./mongodb/mongod.conf:/etc/mongod.conf:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changeme
      - MONGO_INITDB_DATABASE=appdb
    command: ["mongod", "--config", "/etc/mongod.conf"]
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  web-app:
    image: nginx:alpine
    container_name: web-app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app/html:/usr/share/nginx/html:ro
      - ./app/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    depends_on:
      - api

  api:
    image: node:alpine
    container_name: api
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./app/api:/app
    environment:
      - NODE_ENV=production
      - MONGODB_URL=mongodb://root:changeme@mongodb:27017/appdb?authSource=admin
      - PORT=3000
    command: ["npm", "start"]
    networks:
      - app_network
    depends_on:
      mongodb:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=changeme
      - ME_CONFIG_MONGODB_URL=mongodb://root:changeme@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=changeme
    networks:
      - app_network
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
  mongodb_backups:
  redis_data:

networks:
  app_network:
    driver: bridge
