---
all:
  children:
    docker_hosts:
      hosts:
        staging-mongo:
          ansible_host: 192.168.1.100
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    mongo_nodes:
      hosts:
        staging-mongo:
      vars:
        mongo_data_dir: /opt/mongodb/data
        mongo_backup_dir: /opt/mongodb/backups
        mongo_config_dir: /opt/mongodb/config
        mongo_network: mongo_network
