---
all:
  children:
    docker_hosts:
      hosts:
        mongo-node-1:
          ansible_host: 10.0.1.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        mongo-node-2:
          ansible_host: 10.0.1.11
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    mongo_nodes:
      hosts:
        mongo-node-1:
        mongo-node-2:
      vars:
        mongo_data_dir: /opt/mongodb/data
        mongo_backup_dir: /opt/mongodb/backups
        mongo_config_dir: /opt/mongodb/config
        mongo_network: mongo_network
